# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param x A single integer.
#' @export
formatG__new <- function(obj_, ploidy_, default_levels_, obj_ncol_, char_per_allele_, has_rownames_, has_colnames_, colnames_vector_) {
    .Call(`_formatG_formatG__new`, obj_, ploidy_, default_levels_, obj_ncol_, char_per_allele_, has_rownames_, has_colnames_, colnames_vector_)
}

#' @param x A single integer.
#' @export
formatG__process_chunk <- function(ptr, obj_, obj_I_, fun_name_, has_rownames_, token_, NA_action_, howmuch_, where_, what_, input_or_output_, set_ncol_) {
    .Call(`_formatG_formatG__process_chunk`, ptr, obj_, obj_I_, fun_name_, has_rownames_, token_, NA_action_, howmuch_, where_, what_, input_or_output_, set_ncol_)
}

formatG__delete_formatG <- function(ext) {
    .Call(`_formatG_formatG__delete_formatG`, ext)
}

#' export attributes
formatG__get_formatG_parameters <- function(ptr) {
    .Call(`_formatG_formatG__get_formatG_parameters`, ptr)
}

#' @param x A single integer.
#' @export
formatG__reset_state <- function(ptr, reset_lines_, set_ncol_) {
    .Call(`_formatG_formatG__reset_state`, ptr, reset_lines_, set_ncol_)
}

#' @param x A single integer.
#' @export
formatG__loci_to_alleles <- function(ptr) {
    .Call(`_formatG_formatG__loci_to_alleles`, ptr)
}

#' @param x A single integer.
#' @export
formatG__to_numeric <- function(ptr) {
    .Call(`_formatG_formatG__to_numeric`, ptr)
}

#' @param x A single integer.
#' @export
formatG__loci_token_to_alleles <- function(ptr, token_) {
    .Call(`_formatG_formatG__loci_token_to_alleles`, ptr, token_)
}

#' @param x A single integer.
#' @export
formatG__alleles_to_dummy <- function(ptr, NA_policy_) {
    .Call(`_formatG_formatG__alleles_to_dummy`, ptr, NA_policy_)
}

#' @param x A single integer.
#' @export
formatG__get_input <- function(ptr) {
    .Call(`_formatG_formatG__get_input`, ptr)
}

#' @param x A single integer.
#' @export
formatG__get_output <- function(ptr) {
    .Call(`_formatG_formatG__get_output`, ptr)
}

#' @param x A single integer.
#' @export
formatG__get_levels <- function(ptr) {
    .Call(`_formatG_formatG__get_levels`, ptr)
}

formatG__add_chars <- function(ptr, howmuch, where, what) {
    .Call(`_formatG_formatG__add_chars`, ptr, howmuch, where, what)
}

#' @param x A single integer.
#' @export
formatG__alleles_to_loci <- function(ptr, token) {
    .Call(`_formatG_formatG__alleles_to_loci`, ptr, token)
}

#' @param x A single integer.
#' @export
formatG__get_alleles_number <- function(ptr) {
    .Call(`_formatG_formatG__get_alleles_number`, ptr)
}

#' @param x A single integer.
#' @export
formatG__get_alleles_vector <- function(ptr) {
    .Call(`_formatG_formatG__get_alleles_vector`, ptr)
}

#' @param x A single integer.
#' @export
formatG__get_total_alleles <- function(ptr) {
    .Call(`_formatG_formatG__get_total_alleles`, ptr)
}

#' @param x A single integer.
#' @export
formatG__StringM_2_IntM <- function(ptr) {
    .Call(`_formatG_formatG__StringM_2_IntM`, ptr)
}

#' @param x A single integer.
#' @export
formatG__dummy_to_alleles_matrix <- function(ptr) {
    .Call(`_formatG_formatG__dummy_to_alleles_matrix`, ptr)
}

#' formatG
#' @description formatG object constructor
#' @param obj StringMatrix input object  
#' @param ploidy Ploidy of the matrix 
#' @param na_omit NA omit policy (Logical)
NULL

#' process_chunk
#' @description process a chunk using one of the available functions
#' @param data_chunk StringMatrix input object  
#' @param fun_name Name of the function to call
NULL

#' export_attributes
NULL

#' alleles_to_loci
#' @description Creates a individuals x 1 matrix,  with a loci in a column, 
#' from a two-column matrix with the alleles 
#' @param input StringMatrix input object  
#' @param sep character dividing alleles 
NULL

#' alleles_to_loci_matrix
#' @description Wrapper that calls alleles_to_loci for a matrix with multiple loci
#' @param sep character dividing alleles 
NULL

#' add_chars
#' @description Add characters at the beggining/end of each cell of the matrix 
#' referenced in a formatG object
#' @param howmuch Number of characters
#' @param where "start" to add characters at the beginning of the string, 
#' "end" to add characters at the end of the string
#' @param what Character to add
NULL

#' loci_to_alleles
#' @description Split locus in column into alleles in columns
#' @param input individuals x 1 StringMatrix, with locus in column
NULL

#'loci_to_alleles_matrix
#' @description Wrapper that calls loci_to_alleles, 
#' for a matrix with multiple loci, stored in a formatG object
NULL

#' loci_token_to_alleles
#' @description Split locus in column with alleles separated by a character into alleles in columns
#' @param input individuals x 1 StringMatrix, with locus in column
#' @param token  Character separating alleles
NULL

#'loci_token_to_alleles_matrix
#' @description Wrapper that calls loci_token_to_alleles, 
#' for a matrix with multiple loci, stored in a formatG object
#' @param token Character separating alleles
NULL

#' to_numeric
#' @description Recodes a genetic matrix into numernc format
#' @param input individuals x 1 StringMatrix, with locus in column
#' @param this_map key-values list, generated with the formatG object (internal)
NULL

#' to_numeric_matrix
#' @description Wrapper that calls to_numeric, 
#' for a matrix with multiple loci, stored in a formatG object
NULL

#' StringM_2_IntM
#' @description Converts StringMatrix into a IntegerMatrix 
NULL

#' alleles_to_dummy
#' @description Converts a matrix of alleles into a matrix of dummy factors
#' @param input individuals x 2 StringMatrix, with alleles in columns
#' @param NA_action The NA action ("0" or "NA") for recoding NAs.
#' @param this_map key-values list, generated with the formatG object (internal)
#' @param n_alleles Number of alleles present in the loci (internal)
NULL

#' alleles_to_dummy_matrix
#' @description Wrapper that calls alleles_to_dummy,
#' for a matrix with multiple loci (with alleles in columns), stored in a formatG object
NULL

#' dummy_to_alleles
#' @description Inverse operation of alleles_to_dummy
#' @param input individuals x 2 StringMatrix, with alleles in columns
#' @param this_map key-values list, generated with the formatG object (internal)
NULL

#' dummy_to_alleles_matrix
#' @description Wrapper that calls dummy_to_alleles 
#' for a matrix with dummy alleles of multiple loci 
NULL

#' is_unique_size
#' @description Verify if all cells of a matrix have the same number of digits / characters
#' @param input input StringMatrix 
#' 
NULL

#' is_unique_size
#' @description Verify if all cells of a matrix have the same number of digits / characters
#' @param input input IntegerMatrix
NULL

#' size
#' @description Returns the number of characters / digits of a matrix
#' @param input input StingMatrix
NULL

#' size
#' @description Returns the number of characters / digits of a matrix
#' @param input input IntegerMatrix
NULL

#' get_size
#' @description Accessor to the number of characters / digits of a matrix stored in a formatG object
NULL

#' set_levels
#' @description Set the levels of a loci (matrix with alleles in columns, individuals x ploidy)
#' @param input A StringMatrix
NULL

#' set_levels_matrix
#' @description Wrapper for set_levels, to be used
#' @param input A StringMatrix
NULL

#' set_alleles_vector
#' @description Set an internal vector with the number of alleles of each loci
NULL

#' get_input
#' @description Accessor to the input matrix stored in a formatG object
NULL

#' get_output
#' @description Accessor to the output matrix stored in a formatG object
NULL

#' get_levels
#' @description Accessor to internal List with value-keys pairs of a formatG object
NULL

#' get_sexptype
#' @description Accessor to the SEXP type of the output matrix stored in a formatG object
NULL

#' get_alleles_number
#' @description Get the number of alleles stored in a formatG object
NULL

#' get_alleles_vector
#' @description Accessor to internal vector with the number of alleles of each loci
#' 
NULL

#' get_total_alleles
#' @description Get the total number of alleles of the output matrix stored in a formatG object 
NULL

#' reset_state
#' @description Reset state for chunk processing
NULL

#' clear
#' @description Clear a formatG object
NULL

#' validate_string
#' @description Validate the input of a formatG object. Useful for dispatching
#' @param SEXP* args objects passed to the function
#' @param nargs Number of arguments
NULL

#' formatG_finalizer
#' @description finalizer of a formatG object
#' @param formatG* ptr pointer to formatG object
NULL

#' formatG_module
#' @description formatG module
NULL

